baseurl = "https://film.dramaio.net"
title = "drakorindo"
languageCode = "id"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Drakorindo"
  bio = "Redb true identity is unknown"
  avatar = "img/avatar.png"

[Params]
  description = "Download Drama Korea Sub Indo" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  schema = true
  post_meta = ["date"] # Order of post meta information
  
  header = "Drakorindo"
  logos = "img/avatar.png"

[Params.logo]
  subtitle = "Download Drama Korea Sub Indo" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search","recent"]

[Params.widgets]
  recent_num = 8 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
